### ISSUE TITLE
ArgumentError before bootstrap on server create

### ISSUE THREAD

**Issue by yonah-codefresh** [joyent/knife-joyent#91]
I'm using ChefDK 0.4 and knife-joyent 0.4.12.

When I create a ubuntu machine in JPC the server gets created but the bootstrap fails.
My command line looks like this:
knife joyent server create -N nodename -x ubuntu  -I '7735fbba-3706-49f0-8020-9e69e11f8ea1'  -f 'g3-standard-0.5-smartos' --networks '1e7bb0e1-25a9-43b6-bb19-f79ae9540b39,193d6804-256c-4e89-a4cd-46f045959993' --tags '{"owner":"cf", "env":"prod"}' -d cf-cz-ubuntu --no-host-key-verify

Running knife bootstrap manually works.
The error is as follows:
...
Sleeping for 10 seconds
ERROR: ArgumentError: wrong number of arguments (1 for 0)

**Comment by bixu** [comment]
We are also seeing this when using versions of ChefDK > 0.3.5

#dealbreaker :(

**Comment by Marsell** [comment]
Sorry for the long delay. :/

Please give this a spin, and let me know if there are any other problems. I'm not familiar with the Chef ecosystem, but this is in my lap now.
