### ISSUE TITLE
Unable to activate knife-joyent-0.4.12, because chef-12.3.0 conflicts with chef (< 12.1, >= 11.16.2)

### ISSUE THREAD

**Issue by yonah-codefresh** [joyent/knife-joyent#92]

**Comment by bixu** [comment]
I'm also having this problem :(

**Comment by bixu** [comment]
This has been fixed in https://github.com/joyent/knife-joyent/pull/93

**Comment by bixu** [comment]
The latest release via Rubygems.org looks good to me - thanks a bunch!
