### ISSUE TITLE
Compute node no longer shows in `joyent server list`

### ISSUE THREAD

**Issue by hjhart** [joyent/knife-joyent#98]
The below command has a degraded state:

`bundle exec knife joyent server list --show compute_node`

The column where compute_node is empty. Similarly, you cannot sort by the compute_node:

`bundle exec knife joyent server list --show compute_node --sort compute_node`

Presumably, this is still returned by the API but the ruby code is incorrectly parsing the response.

**Comment by numericillustration** [comment]
@hjhart that fix looks good to me.  The compute_node attribute is in fog objects coming from the Fog::Compute::Joyent::Server model code so I'm not sure why it was structured the way it had been.  Thanks
